spring.application.name=patient-service
server.port= 4000

# H2 in-memory DB for local dev
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#
#spring.jpa.database-platform= org.hibernate.dialect.H2Dialect
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.ByteArraySerializer

springdoc.swagger-ui.path=/swagger-ui.html
logging.level.root=info
